- name: Launching vpc
  vpc:
    name: boto3-testing
    state: present
    region: ap-south-1
    cidr_block: 192.168.0.0/16,
  out: vpc_state

- name: launching route table
  rt:
    name: boto3-testing
    state: present
    DestinationCidrBlock: 0.0.0.0/0

- name: launching internet gateway
  internet_gateway:
    name: boto3-testing-ig
    state: present
